// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdbuksqzulqzipznnxzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkYnVrc3F6dWxxemlwem5ueHp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTY5NzQsImV4cCI6MjA2NTQ5Mjk3NH0.V-TKR2kaTVtRY4H6kv0cZqztG6RgcMQeoulV3qfz5RQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);